name: CI
on:
  push:
    branches: [ master, release* ]
    tags: [v*]
  pull_request:
    branches: [ master, release* ]

defaults:
  run: 
    shell: bash

jobs:
  build:
    name: Build job
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby-version: 1.9.3-p551
            bundler-version: 1.17.3
            run-linter: false

          - ruby-version: 2.0.0-p648
            bundler-version: 1.17.3
            run-linter: false

          - ruby-version: 2.1.10
            bundler-version: 1.17.3
            run-linter: false

          - ruby-version: 2.2.10
            bundler-version: 1.17.3
            run-linter: false

          - ruby-version: 2.3.8
            bundler-version: 2.2.32
            run-linter: false

          - ruby-version: 2.4.10
            bundler-version: 2.2.32
            run-linter: false

          - ruby-version: 2.5.8
            bundler-version: 2.2.32
            run-linter: true

          - ruby-version: 2.6.6
            bundler-version: 2.2.32
            run-linter: true

          - ruby-version: 3.0.0
            bundler-version: 2.2.32
            run-linter: true

    container: ruby:${{ matrix.ruby-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Bundler and gems
        run: |
             gem install bundler -v ${{ matrix.bundler-version }}
             bundle install

      - name: Linting
        if: ${{ matrix.run-linter }}
        run: bundle exec standardrb

      - name: Unit Tests
        run: bundle exec rake


  package:
    name: Package the Gem
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - name: Install .NET Core 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: '5.8.1'

      - name: GitVersion Config
        uses: gittools/actions/gitversion/execute@v0.9.11
        with:
          useConfigFile: true
          additionalArguments: '/showConfig'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.11
        id: gitversion
        with:
          useConfigFile: true

      - name: Update the Version
        run: 
          - set -i 's/.*IDE_VERSION=.*/IDE_VERSION=${{ steps.gitversion.outputs.semver }}' lib/ruby-debug-ide/version.rb
          - cat lib/ruby-debug-ide/version.rb

      